/* rankgen.c -- generate tables for rank.c */

#include <stdio.h>

#include "builtins.h"
#include "puzzle.h"
#include "tileset.h"

/*
 * Compute the binomial coefficient (n choose k).
 */
static unsigned choose(unsigned n, unsigned k)
{
	if (k == 0)
		return (1);

	if (k > n)
		return (0);

	if (k > n/2)
		return (choose(n, n - k));

	return (n * (unsigned long long)choose(n - 1, k - 1) / k);
}

/*
 * Compute the rank of m using a direct algorithm.
 */
static unsigned rank(unsigned m)
{
	unsigned sum = 0, i = 1;

	while (m != 0) {
		sum += choose(ctz(m), i++);
		m &= m - 1;
	}

	return (sum);
}

/*
 * Print an entry for one of the lookup tables.  After every group of
 * eight entries, print a newline.
 */
static void
print_entry(unsigned r, unsigned i)
{
	printf("%s%7u,%c", i % 8 == 0 ? "\t" : "", r, i % 8 == 7 ? '\n' : ' ');
}

/*
 * Generate the tables rank_tails, rank_mids, and rank_heads.  This
 * program can be used to regenerate the tables shoudl RANK_SPLIT1 or
 * RANK_SPLIT2 change.
 */
extern int
main()
{
	size_t i, j;

	printf("/* ranktbl.c -- tables generated by util/rankgen.c */\n");
	printf("/* DO NOT EDIT */\n\n");
	printf("#include <tileset.h>\n\n");

	/* generate tails */
	printf("const unsigned short\nrank_tails[1 << RANK_SPLIT1] = {\n");

	for (i = 0; i < 1 << RANK_SPLIT1; i++)
		print_entry(rank(i), i);

	printf("};\n\n");

	/* generate mids */
	printf("const tsrank\nrank_mids[RANK_SPLIT1 + 1][1 << RANK_SPLIT2 - RANK_SPLIT1] = {\n");
	for (i = 0; i < RANK_SPLIT1 + 1; i++) {
		for (j = 0; j < 1 << RANK_SPLIT2 - RANK_SPLIT1; j++)
			print_entry(rank(j << RANK_SPLIT1 | (1 << i) - 1), j);

		printf("%s\n", i == RANK_SPLIT1 ? "};\n" : "");
	}

	/* generate heads */
	printf("const tsrank\nrank_heads[RANK_SPLIT2 + 1][1 << TILE_COUNT - RANK_SPLIT2] = {\n");
	for (i = 0; i < RANK_SPLIT2 + 1; i++) {
		for (j = 0; j < 1 << TILE_COUNT - RANK_SPLIT2; j++)
			print_entry(rank(j << RANK_SPLIT2 | (1 << i) - 1), j);

		printf("%s\n", i == RANK_SPLIT2 ? "};" : "");
	}

	return (0);
}
