/*-
 * Copyright (c) 2017, 2019 Robert Clausecker. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/* rankgen.c -- generate tables for rank.c */

#include <stdio.h>

#include "builtins.h"
#include "puzzle.h"
#include "tileset.h"

/*
 * Compute the binomial coefficient (n choose k).
 */
static unsigned choose(unsigned n, unsigned k)
{
	if (k == 0)
		return (1);

	if (k > n)
		return (0);

	if (k > n/2)
		return (choose(n, n - k));

	return (n * (unsigned long long)choose(n - 1, k - 1) / k);
}

/*
 * Compute the rank of m using a direct algorithm.
 */
static unsigned rank(unsigned m)
{
	unsigned sum = 0, i = 1;

	while (m != 0) {
		sum += choose(ctz(m), i++);
		m &= m - 1;
	}

	return (sum);
}

/*
 * Print an entry for one of the lookup tables.  After every group of
 * eight entries, print a newline.
 */
static void
print_entry(unsigned r, unsigned i)
{
	printf("%s%7u,%c", i % 8 == 0 ? "\t" : "", r, i % 8 == 7 ? '\n' : ' ');
}

/*
 * Generate the tables rank_tails, rank_mids, and rank_heads.  This
 * program can be used to regenerate the tables shoudl RANK_SPLIT1 or
 * RANK_SPLIT2 change.
 */
extern int
main()
{
	size_t i, j;

	printf("/* ranktbl.c -- tables generated by util/rankgen.c */\n");
	printf("/* DO NOT EDIT */\n\n");
	printf("#include <tileset.h>\n\n");

	/* generate tails */
	printf("const tsrank\nrank_tails[1 << RANK_SPLIT1] = {\n");

	for (i = 0; i < 1 << RANK_SPLIT1; i++)
		print_entry(rank(i), i);

	printf("};\n\n");

	/* generate mids */
	printf("const tsrank\nrank_mids[RANK_SPLIT1 + 1][1 << RANK_SPLIT2 - RANK_SPLIT1] = {\n");
	for (i = 0; i < RANK_SPLIT1 + 1; i++) {
		for (j = 0; j < 1 << RANK_SPLIT2 - RANK_SPLIT1; j++)
			print_entry(rank(j << RANK_SPLIT1 | (1 << i) - 1), j);

		printf("%s\n", i == RANK_SPLIT1 ? "};\n" : "");
	}

	/* generate heads */
	printf("const tsrank\nrank_heads[RANK_SPLIT2 + 1][1 << TILE_COUNT - RANK_SPLIT2] = {\n");
	for (i = 0; i < RANK_SPLIT2 + 1; i++) {
		for (j = 0; j < 1 << TILE_COUNT - RANK_SPLIT2; j++)
			print_entry(rank(j << RANK_SPLIT2 | (1 << i) - 1), j);

		printf("%s\n", i == RANK_SPLIT2 ? "};" : "");
	}

	return (0);
}
